const mongoose = require("mongoose");

const mongoose = require('mongoose');

const dataSchema = new mongoose.Schema({
  // --- Respondent & Interviewer Info ---
  email: { type: String, default: null },
  name: { type: String, default: null },
  address: { type: String, default: null },
  contact: { type: Number, default: null },
  interviewerName: { type: String, default: null },
  interviewerId: { type: String, default: null },
  areaName: { type: String, default: null },
  areaCode: { type: String, default: null },
  language: { type: String, default: null },
  // --- Timestamps & Geolocation ---
  startDate: { type: String, default: null },
  startTime: { type: String, default: null },
  endDate: { type: String, default: null },
  endTime: { type: String, default: null },
  duration: { type: String, default: null },
  backST: { type: String, default: null },
  backSD: { type: String, default: null },
  backET: { type: String, default: null },
  backED: { type: String, default: null },
  latitude: { type: Number, default: null },
  longitude: { type: Number, default: null },
  latitude1: { type: Number, default: null },
  longitude1: { type: Number, default: null },
  // --- Screener Questions (QRQ) ---
  QRQ2: { type: String, default: null },
  QRQ3: [{ type: String }],
  QRQ4: { type: String, default: null },
  QRQ5: { type: String, default: null },
  agrGroup: { type: String, default: null },
  QRQ6: { type: String, default: null },
  QRQ7: { type: String, default: null },
  QRQ8: [{ type: String }],
  QRQ9: { type: String, default: null },
  NCCS: { type: String, default: null },
  QRQ10: [{ type: String }],
  QRQ11: [{ type: String }],
  QRQ11_other: { type: String, default: null },
  QRQ11A: [{ type: String }],
  QRQ11A_other: { type: String, default: null },
  QRQ12: [{ type: String }],
  QRQ12_other: { type: String, default: null },
  QRQ13: [{ type: String }],
  QRQ13_other: { type: String, default: null },
  QRQ14: { type: String, default: null },
  QRQ14_other: { type: String, default: null },
  QRQ14_label: { type: String, default: null },
  QRQ14A: { type: String, default: null },
  QRQ15: { type: String, default: null },
  // --- Panel Setup ---
  RecruitmentPanel: { type: String, default: null },
  type: { type: String, default: null },
  panelNumber: { type: String, default: null },
  Panels: [{ type: String }],
  // --- Panel 1 Questions ---
  P1_QMQ1_most: { type: String, default: null },
  P1_QMQ1_least: { type: String, default: null },
  P1_QMQ2a: { type: String, default: null },
  P1_QMQ2b: { type: String, default: null },
  P1_QMQ2c: { type: String, default: null },
  QMQ3_P1: { type: String, default: null },
  QMQ4_P1: { type: String, default: null },
  QMQ5_P1: { type: String, default: null },
  QMQ6_P1: { type: String, default: null },
  P1_QMQ7a: { type: String, default: null },
  P1_QMQ7b: { type: String, default: null },
  P1_QMQ7c: { type: String, default: null },
  P1_QMQ7d: { type: String, default: null },
  P1_QMQ7e: { type: String, default: null },
  P1_QMQ7f: { type: String, default: null },
  QMQ10_P1: [{ type: String }],
  QMQ10_P1_other: { type: String, default: null },
  // --- Panel 2 Questions ---
  P2_QMQ1_most: { type: String, default: null },
  P2_QMQ1_least: { type: String, default: null },
  P2_QMQ2a: { type: String, default: null },
  P2_QMQ2b: { type: String, default: null },
  P2_QMQ2c: { type: String, default: null },
  QMQ3_P2: { type: String, default: null },
  QMQ4_P2: { type: String, default: null },
  QMQ5_P2: { type: String, default: null },
  QMQ6_P2: { type: String, default: null },
  P2_QMQ7a: { type: String, default: null },
  P2_QMQ7b: { type: String, default: null },
  P2_QMQ7c: { type: String, default: null },
  P2_QMQ7d: { type: String, default: null },
  P2_QMQ7e: { type: String, default: null },
  P2_QMQ7f: { type: String, default: null },
  QMQ10_P2: [{ type: String }],
  QMQ10_P2_other: { type: String, default: null },
  // --- Panel 3 Questions ---
  P3_QMQ1_most: { type: String, default: null },
  P3_QMQ1_least: { type: String, default: null },
  P3_QMQ2a: { type: String, default: null },
  P3_QMQ2b: { type: String, default: null },
  P3_QMQ2c: { type: String, default: null },
  QMQ3_P3: { type: String, default: null },
  QMQ4_P3: { type: String, default: null },
  QMQ5_P3: { type: String, default: null },
  QMQ6_P3: { type: String, default: null },
  P3_QMQ7a: { type: String, default: null },
  P3_QMQ7b: { type: String, default: null },
  P3_QMQ7c: { type: String, default: null },
  P3_QMQ7d: { type: String, default: null },
  P3_QMQ7e: { type: String, default: null },
  P3_QMQ7f: { type: String, default: null },
  QMQ10_P3: [{ type: String }],
  QMQ10_P3_other: { type: String, default: null },
  // --- Panel 4 Questions ---
  P4_QMQ1_most: { type: String, default: null },
  P4_QMQ1_least: { type: String, default: null },
  P4_QMQ2a: { type: String, default: null },
  P4_QMQ2b: { type: String, default: null },
  P4_QMQ2c: { type: String, default: null },
  QMQ3_P4: { type: String, default: null },
  QMQ4_P4: { type: String, default: null },
  QMQ5_P4: { type: String, default: null },
  QMQ6_P4: { type: String, default: null },
  P4_QMQ7a: { type: String, default: null },
  P4_QMQ7b: { type: String, default: null },
  P4_QMQ7c: { type: String, default: null },
  P4_QMQ7d: { type: String, default: null },
  P4_QMQ7e: { type: String, default: null },
  P4_QMQ7f: { type: String, default: null },
  QMQ10_P4: [{ type: String }],
  QMQ10_P4_other: { type: String, default: null },
  // --- Panel 5 Questions ---
  P5_QMQ1_most: { type: String, default: null },
  P5_QMQ1_least: { type: String, default: null },
  P5_QMQ2a: { type: String, default: null },
  P5_QMQ2b: { type: String, default: null },
  P5_QMQ2c: { type: String, default: null },
  QMQ3_P5: { type: String, default: null },
  QMQ4_P5: { type: String, default: null },
  QMQ5_P5: { type: String, default: null },
  QMQ6_P5: { type: String, default: null },
  P5_QMQ7a: { type: String, default: null },
  P5_QMQ7b: { type: String, default: null },
  P5_QMQ7c: { type: String, default: null },
  P5_QMQ7d: { type: String, default: null },
  P5_QMQ7e: { type: String, default: null },
  P5_QMQ7f: { type: String, default: null },
  QMQ10_P5: [{ type: String }],
  QMQ10_P5_other: { type: String, default: null },
  // --- Panel 6 Questions ---
  P6_QMQ1_most: { type: String, default: null },
  P6_QMQ1_least: { type: String, default: null },
  P6_QMQ2a: { type: String, default: null },
  P6_QMQ2b: { type: String, default: null },
  P6_QMQ2c: { type: String, default: null },
  QMQ3_P6: { type: String, default: null },
  QMQ4_P6: { type: String, default: null },
  QMQ5_P6: { type: String, default: null },
  QMQ6_P6: { type: String, default: null },
  P6_QMQ7a: { type: String, default: null },
  P6_QMQ7b: { type: String, default: null },
  P6_QMQ7c: { type: String, default: null },
  P6_QMQ7d: { type: String, default: null },
  P6_QMQ7e: { type: String, default: null },
  P6_QMQ7f: { type: String, default: null },
  QMQ10_P6: [{ type: String }],
  QMQ10_P6_other: { type: String, default: null },
  // --- QMQ8 Mappings ---
  QMQ8__1: [{ type: String }],
  QMQ8__2: [{ type: String }],
  QMQ8__3: [{ type: String }],
  QMQ8__4: [{ type: String }],
  QMQ8__5: [{ type: String }],
  QMQ8__6: [{ type: String }],
  QMQ8__7: [{ type: String }],
  QMQ8__8: [{ type: String }],
  QMQ8__9: [{ type: String }],
  QMQ8__10: [{ type: String }],
  QMQ8__11: [{ type: String }],
  QMQ8__12: [{ type: String }],
  QMQ8__13: [{ type: String }],
  QMQ8__14: [{ type: String }],
  QMQ8__15: [{ type: String }],
  QM1b: [{ type: String }],
  QMQ8_16: [{ type: String }],
  QMQ8_17: [{ type: String }],
  // --- Ranking & Promo ---
  rank1: { type: String, default: null },
  rank2: { type: String, default: null },
  rank3: { type: String, default: null },
  rank4: { type: String, default: null },
  rank5: { type: String, default: null },
  rank6: { type: String, default: null },
  promo1: { type: String, default: null },
  promo2: { type: String, default: null },
  promo3: { type: String, default: null },
  promo4: { type: String, default: null },
  promo5: { type: String, default: null },
  promo6: { type: String, default: null },
}, { timestamps: true });

const DataModel = mongoose.model("DataModel", dataSchema);
module.exports = DataModel;

// {
//   "email": "admin",
//   "startDate": "20/08/2025",
//   "startTime": "3:40:51 PM",
//   "backST": "3:40:51 PM",
//   "backSD": "20/08/2025",
//   "areaName": "Boriwali West",
//   "name": "test",
//   "address": "12",
//   "contact": 3232323232,
//   "interviewerName": "21",
//   "interviewerId": "323",
//   "areaCode": "21",
//   "latitude": 18.563072,
//   "longitude": 73.9442688,
//   "language": "en",
//   "QRQ2": "1",
//   "QRQ3": []
//   "QRQ4": "1",
//   "QRQ5": "22",
//   "agrGroup": "21-24 years",
//   "QRQ6": "7",
//   "QRQ7": "5",
//   "QRQ8": [],
//   "QRQ9": "1",
//   "NCCS": "C1",
//   "QRQ10": [],
//   "QRQ11": [],
//   "QRQ14_label": "Hoegaarden",
//   "RecruitmentPanel": "1664 Blanc (BLC)",
//   "type": "BLC",
//   "panelNumber": "6",
//   "Panels": [],
//   "P1_QMQ1_least": "BLC_10",
//   "P2_QMQ1_least": "BLC_10",
//   "QRQ11_other": "21212",
//   "QRQ11A": [],
//   "QRQ11A_other": "21212",
//   "QRQ12": [],
//   "QRQ12_other": "21212",
//   "QRQ13": [],
//   "QRQ13_other": "21212",
//   "QRQ14": "14",
//   "QRQ14_other": "21212",
//   "QRQ14A": "6",
//   "QRQ15": "7",
//   "P4_QMQ1_least": "BLC_5",
//   "P5_QMQ1_least": "BLC_5",
//   "P6_QMQ1_least": "BLC_4",
//   "P1_QMQ2a": "1",
//   "P1_QMQ2b": "2",
//   "P1_QMQ2c": "3",
//   "QMQ3_P1": "122",
//   "QMQ4_P1": "3",
//   "QMQ5_P1": "3",
//   "QMQ6_P1": "4",
//   "P1_QMQ7a": "1",
//   "P1_QMQ7b": "2",
//   "P1_QMQ7c": "3",
//   "P1_QMQ7d": "2",
//   "P1_QMQ7e": "2",
//   "P1_QMQ7f": "2",
//   "P2_QMQ2a": "3",
//   "P2_QMQ2b": "4",
//   "P2_QMQ2c": "5",
//   "QMQ3_P2": "212",
//   "QMQ4_P2": "3",
//   "QMQ5_P2": "2",
//   "QMQ6_P2": "3",
//   "P2_QMQ7a": "1",
//   "P2_QMQ7b": "2",
//   "P2_QMQ7c": "3",
//   "P2_QMQ7d": "3",
//   "P2_QMQ7e": "2",
//   "P2_QMQ7f": "2",
//   "P3_QMQ2a": "3",
//   "P3_QMQ2b": "4",
//   "P3_QMQ2c": "4",
//   "QMQ3_P3": "21221",
//   "QMQ4_P3": "3",
//   "QMQ5_P3": "2",
//   "QMQ6_P3": "2",
//   "P3_QMQ7a": "1",
//   "P3_QMQ7b": "2",
//   "P3_QMQ7c": "3",
//   "P3_QMQ7d": "3",
//   "P3_QMQ7e": "3",
//   "P3_QMQ7f": "3",
//   "P4_QMQ2a": "1",
//   "P4_QMQ2b": "2",
//   "P4_QMQ2c": "3",
//   "QMQ3_P4": "1212",
//   "QMQ4_P4": "3",
//   "QMQ5_P4": "1",
//   "QMQ6_P4": "3",
//   "P4_QMQ7a": "1",
//   "P4_QMQ7b": "2",
//   "P4_QMQ7c": "3",
//   "P4_QMQ7d": "3",
//   "P4_QMQ7e": "3",
//   "P4_QMQ7f": "3",
//   "P5_QMQ2a": "2",
//   "P5_QMQ2b": "3",
//   "P5_QMQ2c": "3",
//   "QMQ3_P5": "qww",
//   "QMQ4_P5": "3",
//   "QMQ5_P5": "2",
//   "QMQ6_P5": "3",
//   "P5_QMQ7a": "1",
//   "P5_QMQ7b": "2",
//   "P5_QMQ7c": "3",
//   "P5_QMQ7d": "3",
//   "P5_QMQ7e": "3",
//   "P5_QMQ7f": "3",
//   "P6_QMQ2a": "1",
//   "P6_QMQ2b": "2",
//   "P6_QMQ2c": "3",
//   "QMQ3_P6": "qww",
//   "QMQ4_P6": "3",
//   "QMQ5_P6": "2",
//   "QMQ6_P6": "3",
//   "P6_QMQ7a": "1",
//   "P6_QMQ7b": "2",
//   "P6_QMQ7c": "3",
//   "P6_QMQ7d": "3",
//   "P6_QMQ7e": "3",
//   "P6_QMQ7f": "3",
//   "QMQ8__1": [],
//   "QMQ8__2": [],
//   "QMQ8__3": [ ],
//   "QMQ8__4": [],
//   "QMQ8__5": [],
//   "QMQ8__6": [],
//   "QMQ8__7": [ ],
//   "QMQ8__8": [],
//   "QMQ8__9": [],
//   "QMQ8__10": [],
//   "QMQ8__11": [],
//   "QMQ8__12": [],
//   "QMQ8__13": [],
//   "QMQ8__14": [],
//   "QMQ8__15": [],
//   "rank5": "BLC_9",
//   "rank4": "BLC_1",
//   "rank3": "BLC_11",
//   "rank2": "BLC_7",
//   "rank6": "BLC_12",
//   "rank1": "BLC_6",
//   "P1_QMQ1_most": "BLC_9",
//   "P2_QMQ1_most": "BLC_6",
//   "P3_QMQ1_most": "BLC_6",
//   "P3_QMQ1_least": "BLC_9",
//   "P4_QMQ1_most": "BLC_7",
//   "P5_QMQ1_most": "BLC_6",
//   "P6_QMQ1_most": "BLC_9",
//   "promo1": "BLC_6",
//   "promo2": "BLC_7",
//   "promo3": "BLC_9",
//   "promo4": "BLC_1",
//   "promo5": "BLC_11",
//   "promo6": "BLC_12",
//   "QMQ10_P1": [],
//   "QMQ10_P2": [],
//   "QMQ10_P3": [],
//   "QMQ10_P4": [],
//   "QMQ10_P5": [],
//   "QMQ10_P6": [ ],
//   "QMQ10_P6_other": "323232",
//    "duration": "00:00:47",
// "endDate": "20/08/2025",
// "endTime": "4:23:38 PM",
// "backED": "20/08/2025",
// "backET": "4:23:38 PM" ,
// "longitude1": 73.9442688,
// "latitude1": 18.563072
// }
//214 to 389=175