const mongoose = require("mongoose");

const dataSchema = new mongoose.Schema({
  email: { type: String, default: null },
  startDate: { type: String, default: null },
  startTime: { type: String, default: null },
  QRQ2: { type: String, default: null },
  name: { type: String, default: null },
  address: { type: String, default: null },
  contact: { type: Number, default: null },
  interviewerName: { type: String, default: null },
  interviewerId: { type: String, default: null },
  areaName: { type: String, default: null },
  areaCode: { type: String, default: null },
  latitude: { type: Number, default: null },
  longitude: { type: Number, default: null },
  language: { type: String, default: null },
  backST: { type: String, default: null },
  backSD: { type: String, default: null },

  QRQ3: [{ type: String }],
  QRQ4: { type: String, default: null },
  QRQ5: { type: String, default: null },
  agrGroup: { type: String, default: null },
  QRQ6: { type: String, default: null },
  QRQ7: { type: String, default: null },
  QRQ8: [{ type: String }],
  NCCS: { type: String, default: null },
  QRQ9: { type: String, default: null },
  QRQ10: [{ type: String }],
  QRQ11: [{ type: String }],
  QRQ11_other: { type: String, default: null },
  QRQ11A: [{ type: String }],
  QRQ11A_other: { type: String, default: null },
  QRQ12: [{ type: String }],
  QRQ12_other: { type: String, default: null },
  QRQ13: [{ type: String }],
  QRQ13_other: { type: String, default: null },

  QRQ14: { type: String, default: null },
  QRQ14_label: { type: String, default: null },
  RecruitmentPanel: { type: String, default: null },
  type: { type: String, default: null },
  panelNumber: { type: String, default: null },
  Panels: [{ type: String }],

  P1_QMQ1_most: { type: String, default: null },
  P1_QMQ1_least: { type: String, default: null },
  P2_QMQ1_most: { type: String, default: null },
  P2_QMQ1_least: { type: String, default: null },
  P3_QMQ1_most: { type: String, default: null },
  P3_QMQ1_least: { type: String, default: null },
  P4_QMQ1_most: { type: String, default: null },
  P4_QMQ1_least: { type: String, default: null },
  P5_QMQ1_most: { type: String, default: null },
  P5_QMQ1_least: { type: String, default: null },
  P6_QMQ1_most: { type: String, default: null },
  P6_QMQ1_least: { type: String, default: null },

  QRQ14A: { type: String, default: null },
  QRQ15: { type: String, default: null },

  QMQ1b: [{ type: String }],

  // Panel-wise ratings
  P1_QMQ2a: { type: String, default: null },
  P1_QMQ2a_label: { type: String, default: null },
  P1_QMQ2b: { type: String, default: null },
  P1_QMQ2b_label: { type: String, default: null },
  P1_QMQ2c: { type: String, default: null },
  P1_QMQ2c_label: { type: String, default: null },
  QMQ3_P1: { type: String, default: null },
  QMQ4_P1: { type: String, default: null },
  QMQ5_P1: { type: String, default: null },
  QMQ6_P1: { type: String, default: null },

  P1_QMQ7a: { type: String, default: null },
  P1_QMQ7a_label: { type: String, default: null },
  P1_QMQ7b: { type: String, default: null },
  P1_QMQ7b_label: { type: String, default: null },
  P1_QMQ7c: { type: String, default: null },
  P1_QMQ7c_label: { type: String, default: null },
  P1_QMQ7d: { type: String, default: null },
  P1_QMQ7d_label: { type: String, default: null },
  P1_QMQ7e: { type: String, default: null },
  P1_QMQ7e_label: { type: String, default: null },
  P1_QMQ7f: { type: String, default: null },
  P1_QMQ7f_label: { type: String, default: null },

  // Panel 2 ratings
  P2_QMQ2a: { type: String, default: null },
  P2_QMQ2a_label: { type: String, default: null },
  P2_QMQ2b: { type: String, default: null },
  P2_QMQ2b_label: { type: String, default: null },
  P2_QMQ2c: { type: String, default: null },
  P2_QMQ2c_label: { type: String, default: null },
  QMQ3_P2: { type: String, default: null },
  QMQ4_P2: { type: String, default: null },
  QMQ5_P2: { type: String, default: null },
  QMQ6_P2: { type: String, default: null },
  P2_QMQ7a: { type: String, default: null },
  P2_QMQ7a_label: { type: String, default: null },
  P2_QMQ7b: { type: String, default: null },
  P2_QMQ7b_label: { type: String, default: null },
  P2_QMQ7c: { type: String, default: null },
  P2_QMQ7c_label: { type: String, default: null },
  P2_QMQ7d: { type: String, default: null },
  P2_QMQ7d_label: { type: String, default: null },
  P2_QMQ7e: { type: String, default: null },
  P2_QMQ7e_label: { type: String, default: null },
  P2_QMQ7f: { type: String, default: null },
  P2_QMQ7f_label: { type: String, default: null },

  // Ranking & QMQ8 mapping
  QMQ8__1: { type: String, default: null },
  QMQ8__2: { type: String, default: null },
  QMQ8__3: { type: String, default: null },
  QMQ8__4: { type: String, default: null },
  QMQ8__5: { type: String, default: null },
  QMQ8__6: { type: String, default: null },
  QMQ8__7: { type: String, default: null },
  QMQ8__8: { type: String, default: null },
  QMQ8__9: { type: String, default: null },
  QMQ8__10: { type: String, default: null },
  QMQ8__11: { type: String, default: null },
  QMQ8__12: { type: String, default: null },
  QMQ8__13: { type: String, default: null },
  QMQ8__14: { type: String, default: null },
  QMQ8__15: { type: String, default: null },
  QMQ8__16: { type: String, default: null },
  QMQ8__17: { type: String, default: null },

  Rank1: { type: String, default: null },
  Rank2: { type: String, default: null },
  Rank3: { type: String, default: null },
  Rank4: { type: String, default: null },
  Rank5: { type: String, default: null },
  Rank6: { type: String, default: null },

  QMQ10: [{ type: String }],
  QMQ10_other: { type: String, default: null },

  P3_QMQ2a: { type: String, default: null },
  P3_QMQ2a_label: { type: String, default: null },
  P3_QMQ2b: { type: String, default: null },
  P3_QMQ2b_label: { type: String, default: null },
  P3_QMQ2c: { type: String, default: null },
  P3_QMQ2c_label: { type: String, default: null },
  QMQ3_P3: { type: String, default: null },
  QMQ4_P3: { type: String, default: null },
  QMQ5_P3: { type: String, default: null },
  QMQ6_P3: { type: String, default: null },
  P3_QMQ7a: { type: String, default: null },
  P3_QMQ7a_label: { type: String, default: null },
  P3_QMQ7b: { type: String, default: null },
  P3_QMQ7b_label: { type: String, default: null },
  P3_QMQ7c: { type: String, default: null },
  P3_QMQ7c_label: { type: String, default: null },
  P3_QMQ7d: { type: String, default: null },
  P3_QMQ7d_label: { type: String, default: null },
  P3_QMQ7e: { type: String, default: null },
  P3_QMQ7e_label: { type: String, default: null },
  P3_QMQ7f: { type: String, default: null },
  P3_QMQ7f_label: { type: String, default: null },

  P4_QMQ2a: { type: String, default: null },
  P4_QMQ2a_label: { type: String, default: null },
  P4_QMQ2b: { type: String, default: null },
  P4_QMQ2b_label: { type: String, default: null },
  P4_QMQ2c: { type: String, default: null },
  P4_QMQ2c_label: { type: String, default: null },
  QMQ3_P4: { type: String, default: null },
  QMQ4_P4: { type: String, default: null },
  QMQ5_P4: { type: String, default: null },
  QMQ6_P4: { type: String, default: null },
  P4_QMQ7a: { type: String, default: null },
  P4_QMQ7a_label: { type: String, default: null },
  P4_QMQ7b: { type: String, default: null },
  P4_QMQ7b_label: { type: String, default: null },
  P4_QMQ7c: { type: String, default: null },
  P4_QMQ7c_label: { type: String, default: null },
  P4_QMQ7d: { type: String, default: null },
  P4_QMQ7d_label: { type: String, default: null },
  P4_QMQ7e: { type: String, default: null },
  P4_QMQ7e_label: { type: String, default: null },
  P4_QMQ7f: { type: String, default: null },
  P4_QMQ7f_label: { type: String, default: null },

  P5_QMQ2a: { type: String, default: null },
  P5_QMQ2a_label: { type: String, default: null },
  P5_QMQ2b: { type: String, default: null },
  P5_QMQ2b_label: { type: String, default: null },
  P5_QMQ2c: { type: String, default: null },
  P5_QMQ2c_label: { type: String, default: null },
  QMQ3_P5: { type: String, default: null },
  QMQ4_P5: { type: String, default: null },
  QMQ5_P5: { type: String, default: null },
  QMQ6_P5: { type: String, default: null },
  P5_QMQ7a: { type: String, default: null },
  P5_QMQ7a_label: { type: String, default: null },
  P5_QMQ7b: { type: String, default: null },
  P5_QMQ7b_label: { type: String, default: null },
  P5_QMQ7c: { type: String, default: null },
  P5_QMQ7c_label: { type: String, default: null },
  P5_QMQ7d: { type: String, default: null },
  P5_QMQ7d_label: { type: String, default: null },
  P5_QMQ7e: { type: String, default: null },
  P5_QMQ7e_label: { type: String, default: null },
  P5_QMQ7f: { type: String, default: null },
  P5_QMQ7f_label: { type: String, default: null },

  P6_QMQ2a: { type: String, default: null },
  P6_QMQ2a_label: { type: String, default: null },
  P6_QMQ2b: { type: String, default: null },
  P6_QMQ2b_label: { type: String, default: null },
  P6_QMQ2c: { type: String, default: null },
  P6_QMQ2c_label: { type: String, default: null },
  QMQ3_P6: { type: String, default: null },
  QMQ4_P6: { type: String, default: null },
  QMQ5_P6: { type: String, default: null },
  QMQ6_P6: { type: String, default: null },
  P6_QMQ7a: { type: String, default: null },
  P6_QMQ7a_label: { type: String, default: null },
  P6_QMQ7b: { type: String, default: null },
  P6_QMQ7b_label: { type: String, default: null },
  P6_QMQ7c: { type: String, default: null },
  P6_QMQ7c_label: { type: String, default: null },
  P6_QMQ7d: { type: String, default: null },
  P6_QMQ7d_label: { type: String, default: null },
  P6_QMQ7e: { type: String, default: null },
  P6_QMQ7e_label: { type: String, default: null },
  P6_QMQ7f: { type: String, default: null },
  P6_QMQ7f_label: { type: String, default: null },

  QRQ14_other: { type: String, default: null },

  duration: { type: String, default: null },
  endTime: { type: String, default: null },
  endDate: { type: String, default: null },
  backET: { type: String, default: null },
  backED: { type: String, default: null },

  latitude1: { type: Number, default: null },
  longitude1: { type: Number, default: null }
}, { timestamps: true });

const DataModel = mongoose.model("DataModel", dataSchema);
module.exports = DataModel;